[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd backend && npm ci --omit=dev"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"